# Generated by Django 3.2 on 2024-11-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('etnia', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=3)),
                ('numero_emergencia', models.CharField(max_length=15)),
                ('colegio_procedencia', models.CharField(max_length=200)),
                ('beneficio_junaeb', models.CharField(choices=[('Beca_men', 'Beca de Alimentación Escolar'), ('Beca_enseñanza', 'Beca de Enseñanza Media'), ('Beca_presupuesto', 'Beca Presidente de la República'), ('Beca_pase', 'Beca PASE (Beca de Acceso a la Educación Superior)'), ('Subsidio_transporte', 'Subsidio de Transporte'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=20)),
                ('sistema_salud', models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Privado', 'Salud Privada'), ('Ninguno', 'Sin Sistema de Salud')], default='Ninguno', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
