# Generated by Django 3.2 on 2024-11-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('run', models.CharField(max_length=12, unique=True, verbose_name='RUN')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('oficio', models.CharField(max_length=100, verbose_name='Oficio')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('nivel_educacional', models.CharField(choices=[('Básico', 'Básico'), ('Medio', 'Medio'), ('Técnico', 'Técnico'), ('Universitario', 'Universitario'), ('Otro', 'Otro')], max_length=50, verbose_name='Nivel Educacional')),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='beneficio_junaeb',
            field=models.CharField(choices=[('Beca_baes', 'Beca de Alimentación Escolar'), ('Beca_enseñanza', 'Beca de Enseñanza Media'), ('Beca_presidente', 'Beca Presidente de la República'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=20),
        ),
    ]
