# Generated by Django 3.2 on 2024-11-24 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingApp', '0004_alter_apoderado_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='ingApp.apoderado'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoderados', to='ingApp.alumno'),
        ),
    ]
