# Generated by Django 3.2 on 2024-11-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingApp', '0005_auto_20241123_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='nivel_educacional',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('ed_basica', 'Educación Básica'), ('ed_media', 'Educación Media'), ('ed_superior', 'Educación Superior'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=20),
        ),
    ]
